# Generated by Django 3.2 on 2022-04-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('G1', 'Guest 1'), ('G2', 'Guest 2'), ('G3', 'Guest 3'), ('G4', 'Guest 4'), ('G5', 'Guest 5'), ('G6', 'Guest 6')], default='G1', max_length=6)),
            ],
        ),
    ]
