# Generated by Django 3.2 on 2022-08-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_pictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Picture',
        ),
    ]
