# Generated by Django 3.2 on 2022-08-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_rename_pictures_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
